FROM alpine:3.4

# Dex connectors, such as GitHub and Google logins require root certificates.
# Proper installations should manage those certificates, but it's a bad user
# experience when this doesn't work out of the box.
#
# OpenSSL is required so wget can query HTTPS endpoints for health checking.

RUN apk add --update ca-certificates openssl

COPY _output/bin/example-app /bin/example-app
RUN mkdir -p /static
COPY _output/static/ /static

WORKDIR /

ENTRYPOINT ["./bin/example-app"]

EXPOSE 5555

CMD ["version"]
