#!/bin/bash -e

mkdir -p _output/bin

sudo docker build -f Dockerfile-base -t golang-updated .

sudo docker run \
    --cidfile=cid \
    -v $PWD:/go/src/github.com/coreos/dex:ro \
    -w /go/src/github.com/coreos/dex \
    golang-updated \
    /bin/sh -x -c \
    'make release-binary'

sudo docker cp $( cat cid ):/go/bin/dex _output/bin/dex
sudo docker rm $( cat cid )
sudo rm cid
